### ISSUE TITLE
Fails when radial-gradient shape is omitted but a size is provided

### ISSUE THREAD

**Issue by gilmoreorless** [rafaelcaricio/gradient-parser#4]
The [radial-gradient spec](http://www.w3.org/TR/css3-images/#radial-gradients) says that both _shape_ and _size_ are optional.

Gradient Parser works with most cases, but it fails in the specific case when a size is given (such as "furthest-corner") but a shape is omitted.

Example: https://jsbin.com/gogelo/5/edit?html,js,console

**Comment by rafaelcaricio** [comment]
Thank you for pointing this out and sorry for the very late fix.

**Comment by pixelspark** [comment]
@rafaelcaricio it looks like the built version was not updated: the error still exists in https://github.com/rafaelcaricio/gradient-parser/blob/master/build/node.js#L267. Would you mind updating the build as well?

**Comment by rafaelcaricio** [comment]
I will have a look. I did something wrong.. 🤦🏽
